language: node_js
node_js:
- '12'
- '10'
script: npm run ci
cache: npm

deploy:
  edge: true
  provider: npm
  email: njirem@gmail.com
  tag: latest
  skip_cleanup: true
  on:
    branch: master
    tags: true
    node: 10
